### ISSUE TITLE
Missing nuget GenericServices and GenericSecurity

### ISSUE THREAD

**Issue by roelang** [JonPSmith/SampleMvcWebApp#1]
Great work and example! I am missing these two libraries. Cant find GenericServices in nuget and GenericSecurity.

I downloaded GenericServices and reference manually (not nuget) but GenericSecurity is cannot resolve.

Please help, when you get a chance.

Thanks
Roel

**Comment by JonPSmith** [comment]
Hi @roelang. The libraries are moving fast at the moment so things aren't stable. I therefore cut a release [Beta4-3](https://github.com/JonPSmith/GenericServices/releases/tag/Beta4-3) a while back that SampleMvcWebApp uses so pull that version down to get SampleMvcWebApp working. There is a binary if that helps.

Do have a play but be aware I have a lot of changes in the pipeline so its not going to be stable for a while.

**Comment by roelang** [comment]
Thanks Jon. What about GenericSecurity? Is there a dll on this too? Thanks

**Comment by JonPSmith** [comment]
Hi @roelang. Ah, I thought I froze SampleMvcWebApp before adding GenericSecurity, which is not an open-source libaray. If you take [this version of SampleMvcWebApp](https://github.com/JonPSmith/SampleMvcWebApp/tree/abb3625755a9760dadd5ebd111fcd04939aee63d) then that was just before I move the code out. In that version, which I will tag at some stage, the security stuff was mixed in with the main application. 

My long term aim is to focus GenericServices and SampleMvcWebApp solely on data access and transformation. The current demo/code tries to do too many things and is much too complicated because of it.

**Comment by JonPSmith** [comment]
Hi @roelang. Sorry, but I was in a hurry for an important business meeting and the version you should use is one back from the one I mentioned. I have now tagged is and made it a pre-release. You can [find it here](https://github.com/JonPSmith/SampleMvcWebApp/releases/tag/Pre-GenericSecurity)

**Comment by roelang** [comment]
Thanks Jon. I really appreciate and not to cause pressure on you. What I want is to be able to run the app locally to check the data access and dto as what you've intended.

**Comment by JonPSmith** [comment]
Hi @roelang. Just to say I have now got SampleMvcWebApp and [GenericServices](https://github.com/JonPSmith/GenericServices) in step. I have removed all the action and SQL security items so its just about CRUD operations and DTOs. That removes some of the fancy stuff like SQL security demo, but makes a more focused test bed for GenericServices. 

Let me know if you have any problems.

**Comment by JonPSmith** [comment]
Closing this with the release of a NuGet package for GenericServices.
